config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

    devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

	namespace :admin do
    root 'chapters#index'

		resources :pages, only: [:index, :new, :edit, :create, :update, :destroy]
		resources :users, only: [:index, :show, :new, :edit, :create, :update]

		resources :chapters do
			resources :pages
		end
	end

	get 'home/:title' => 'home#index'
	get 'states/:id', to: 'states#show', as: :state
	get 'chapters/:id', to: 'chapters#show', as: :chapter
	get 'pages/:id', to: 'pages#show', as: :page

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/admin/pages/_form.html.erb
<%= form_for([:admin, @page]) do |f| %>
  <%- if @page.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@page.errors.count, "error") %> prohibited
        this page from being saved:
      </h2>
      <ul>
        <%- @page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%- end %>
      </ul>
    </div>
  <%- end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :sub_title %><br>
    <%= f.text_field :sub_title %>
  </p>
  <div>
    <%= f.label :body %><br>
    <%#= f.text_area :body, :cols => 80, :rows => 20 %>
    <%= f.bootsy_area :body, :cols => 110, :rows => 20 %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<%- end %>
<%= link_to 'Back', admin_pages_path(@page) %>

app/views/admin/pages/_form_polymorphic.html.erb
<%- unless @page %>
  <%- @page = pageable.build_page %>
<%- end %>
<%= form_for([:admin, pageable, @page]) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@page.errors.count, "error") %> prohibited
        this chapter from being saved:
      </h2>
      <ul>
        <% @page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :sub_title %><br>
    <%= f.text_field :sub_title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, :cols => 80, :rows => 20 %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', polymorphic_path([:admin, pageable]) %>

app/views/admin/pages/_pages_table.html.erb
<div class="panel panel-default">
  <table class="table">
    <tr>
      <th>Title</th>
      <th >Sub-Title</th>
      <th>Body</th>
      <th colspan="2"></th>
    </tr>

    <% pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.sub_title %></td>
        <td><%= page.body.html_safe %></td>
        <td>
        <%- if page.pageable %>
          <%= link_to edit_admin_chapter_page_path(page.pageable, page) do %>
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
          <% end %>
        <%- else %>
          <%= link_to edit_admin_page_path(page) do %>
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
          <% end %>
        <%- end %>
        </td>
        <td>
        <%= link_to admin_page_path(page), method: :delete, data: { confirm: 'Are you sure?' } do%>
          <span class="glyphicon glyphicon-remove" style="color:red" aria-hidden="true"></span>
        <%- end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/pages/edit.html.erb
<%- if @pageable.present? %>
  <div class="page-header">
    <h1>Edit <%= @pageable.name %> <%= @page.pageable_type %> Page</h1>
  </div>
  <%= render 'form_polymorphic', :pageable => @pageable %>
<%- else %>
  <div class="page-header">
    <h1>Edit <%= @page.title %> Page</h1>
  </div>
  <%= render 'form' %>
<%- end %>

app/views/admin/pages/index.html.erb
<div class="page-header">
  <h1>Pages</h1>
</div>

<%= render partial: "pages_table", locals: { pages: @pages, description: '' } %>

app/views/admin/pages/new.html.erb
<h1>New Page</h1>
<%= render 'form' %>