config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

    devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

	namespace :admin do
    root 'chapters#index'

		resources :pages, only: [:index, :new, :edit, :create, :update, :destroy]
		resources :users, only: [:index, :show, :new, :edit, :create, :update]

		resources :chapters do
			resources :pages
		end
	end

	get 'home/:title' => 'home#index'
	get 'states/:id', to: 'states#show', as: :state
	get 'chapters/:id', to: 'chapters#show', as: :chapter
	get 'pages/:id', to: 'pages#show', as: :page

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/admin/_header.html.erb
<head>
  <title>Killer Mans Sons</title>
	<!-- Latest compiled and minified JavaScript -->
  <%= csrf_meta_tags %>
	<!-- Latest compiled and minified CSS for bootstrap-->
	<!-- Optional theme -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    "admin/application", :media => "all" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

	<meta name="viewport" content="width=device-width, initial-scale=1">

</head>

app/views/layouts/admin/_nav_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to(admin_root_path, class: "navbar-brand")do %>
        <span class="glyphicon glyphicon-road" aria-hidden="true"></span>
      <%- end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <%= link_to admin_chapters_path, class: 'dropdown-toggle', :'data-toggle' => 'dropdown', role: "button", :'aria-haspopup' => 'true', :'aria-expanded' => 'false' do %>
            Chapters <span class="caret"></span>
          <%- end %>
          <ul class="dropdown-menu">
            <li><%= link_to 'New', new_admin_chapter_path %></li>
            <li><%= link_to 'All', admin_chapters_path %></li>
            <%- Chapter.all.order(:name).each do |chapter| %>
              <li><%= link_to chapter.name, admin_chapter_path(chapter) %></li>
            <%- end %>
          </ul>
        </li>
        <li class="dropdown">
          <%= link_to '#', class: 'dropdown-toggle', :'data-toggle' => 'dropdown', role: "button", :'aria-haspopup' => 'true', :'aria-expanded' => 'false' do -%>
            Pages<span class="caret"></span>
          <%- end %>
          <ul class="dropdown-menu">
            <li><%= link_to 'New', new_admin_page_path %></li>
            <li><%= link_to 'View', admin_pages_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <%= link_to '#', class: 'dropdown-toggle', :'data-toggle' => 'dropdown', role: "button", :'aria-haspopup' => 'true', :'aria-expanded' => 'false' do -%>
            Members<span class="caret"></span>
          <%- end %>
          <ul class="dropdown-menu">
            <li><%= link_to 'View', admin_users_path %></li>
            <li><%= link_to 'New', new_admin_user_path %></li>
          </ul>
        </li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%- if Rails.env.development? %>
        <li class="dropdown ">
          <%= link_to admin_pages_path, class: 'dropdown-toggle', :'data-toggle' => 'dropdown', role: "button", :'aria-haspopup' => 'true', :'aria-expanded' => 'false' do %>
            Debug <span class="caret"></span>
          <%- end %>
          <ul class="dropdown-menu">
            <li><%= link_to 'Letter Opener', letter_opener_web_path, :target => '_blank' %></li>
          </ul>
        </li>
        <%- end %>
        <li>
        <%- if user_signed_in? %>
          <%= link_to("Signed in as #{current_user.email}", destroy_user_session_path, class: 'navbar-link', :method => :delete) %>
        <%- else %>
          <%= link_to('Login', new_user_session_path)  %>
        <%- end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin/_notification.html.erb
<%- if notice %>
  <p class="alert alert-success"><%= notice %></p>
<%- end %>
<%- if alert %>
	<p class="alert alert-danger"><%= alert %></p>
<%- end %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
	<%= render 'layouts/admin/header' %>
<body>
	<%= render 'layouts/admin/nav_bar' %>
	<%= render 'layouts/admin/notification' %>
<div class="container-fluid">
<%= yield %>
</div>

</body>
</html>