config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

    devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

	namespace :admin do
    root 'chapters#index'

		resources :pages, only: [:index, :new, :edit, :create, :update, :destroy]
		resources :users, only: [:index, :show, :new, :edit, :create, :update]

		resources :chapters do
			resources :pages
		end
	end

	get 'home/:title' => 'home#index'
	get 'states/:id', to: 'states#show', as: :state
	get 'chapters/:id', to: 'chapters#show', as: :chapter
	get 'pages/:id', to: 'pages#show', as: :page

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	scope :orphaned, -> { where(chapter_id: nil) }

  belongs_to :chapter
  has_one :address, :as => :addressable, dependent: :destroy
    accepts_nested_attributes_for :address

  before_create :set_default_role

  ### Include default devise modules. Others available are:
  ### :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  royce_roles %w[president vice_president sgt_at_arms treasurer secretary road_captain member marauder prospect]

  def name
    "#{self[:name_first]} #{self[:name_last]}".titleize
  end

  private
    def set_default_role
      self.add_role :prospect
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  ### A frequent practice is to place the standard CRUD actions in each
  ### controller in the following order: index, show, new, edit, create, update
  ### and destroy
  def index
    @chapters = Chapter.all
  end

  def show
    @user = User.includes(:chapter).includes(:address).find(params[:id])
  end

  def new
    @user = User.new
    @user.password = Devise.friendly_token.first(8)
    @user.build_address
  end

  def edit
    @user = User.find(params[:id])

    if @user.address.nil?
      @user.build_address
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to [:admin, @user]
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      update_roles
      redirect_to [:admin, @user]
    else
      render 'edit'
    end
  end

  private
  def user_params
    ### Remove the password key of the params hash if it’s blank.
    ### If not, Devise will fail to validate.
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    params.require(:user).permit(
      :name_first, :name_last, :chapter_id, :email, :password,
      address_attributes: [:id, :line_1, :line_2, :city, :state_id, :postal_code]
    )
  end

  def user_params_update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    params.require(:user).permit(
      :name_first, :name_last, :chapter_id, :email, :password,
      address_attributes: [:id, :line_1, :line_2, :city, :state_id, :postal_code],
      :role_names => []
    )
  end

  def update_roles
    existing_roles = @user.role_list || []
    new_roles = user_params_update[:role_names] || []

    remove_roles = existing_roles - new_roles
    remove_roles.each do |role_name|
      @user.remove_role role_name
    end

    add_roles = new_roles - existing_roles
    add_roles.each do |role_name|
      if @user.allowed_role? role_name
        @user.add_role role_name
      end
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def sort_users_by_role(users)
    sorted = []
    visited = {}

    role_order.each do |role_name|
      users.each do |user|
        next if visited[user.id]

        if user.has_role? role_name
          sorted.push( user )

          visited[user.id] = true
        end
      end
    end

    return sorted
  end

  def role_order
    User.available_role_names
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%- if @user.errors.any? %>
    <div class="alert alert-warning" role="alert">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this chapter from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <%- end %>
  <%- if !@user.address.nil? and @user.address.errors.any? %>
    <div class="alert alert-warning" role="alert">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this chapter from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <%- end %>

  <fieldset class="form-group">
    <%= f.label :name_first, 'First Name' %>
    <div class="input-group">
      <%= f.text_field :name_first, class: "form-control", placeholder: "First Name", :'aria-describedby' => "Member's first name"%>
    </div>
  </fieldset>

  <%- unless @user.persisted? %>
    <%= f.hidden_field :password, :value => @user.password %>
  <%- end %>

  <fieldset class="form-group">
    <%= f.label :name_last, 'Last Name' %>
    <div class="input-group">
      <%= f.text_field :name_last, class: "form-control", placeholder: "Last Name", :'aria-describedby' => "Member's last name"%>
    </div>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :email %>
    <div class="input-group">
      <span class="input-group-addon">@</span>
      <%= f.email_field :email, class: "form-control", placeholder: "Email Address", :'aria-describedby' => "Member's email address"%>
    </div>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :chapter %>
    <div class="input-group">
      <%= f.collection_select :chapter_id, Chapter.order(:name), :id, :titleize_name, {prompt: true}, {class: 'form-control'} %>
    </div>
  </fieldset>

  <%= render :partial => 'user_role_checkboxes', :locals => {f: f, user: @user} %>

  <%= f.fields_for :address do |address| %>
    <%= render :partial => 'admin/addresses/address', :locals => {:f => address} %>
  <%- end %>

  <div class="input-group">
    <%= f.submit "Save", class: "btn btn-primary btn-sm " %>
    <%#= link_to 'Back', admin_chapters_path, class: 'btn btn-default btn-sm'%>
  </div>
<%- end %>

app/views/admin/users/_user_role_checkboxes.html.erb
<fieldset class="form-group">
	<%= f.label :role %>
	<div class="input-group">
		<% user.class.available_role_names.each do |role_name| %>
			<div class="checkbox">
				<label>
					<% if user.has_role? role_name %>
						<% checked = true %>
					<% else %>
						<% checked = false %>
					<% end %>
					<%= check_box_tag 'user[role_names][]', role_name, user.has_role?(role_name) -%>
					<%= role_name.titleize -%>
				</label>
			</div>
		<%- end %>
	</div>
</fieldset>

app/views/admin/users/_users_table.html.erb
<div class="panel panel-default">
  <table class="table">
    <caption>
      <%- if !chapter.nil? %>
        <%= chapter.name %>
      <% else %>
        Members who haven't been assigned to a chapter
      <% end %>
    </caption>
    <thead>
      <tr>
        <th>Position</th>
        <th>Name</th>
        <th>Email</th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= user.role_list.map{|role_name| role_name.titleize}.join(', ') %></td>
        <td><%= user.name_first %> <%= user.name_last %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to admin_user_path(user) do%>
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
          <%- end %>
        </td>
        <td>
          <%= link_to edit_admin_user_path(user) do%>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <%- end %>
        </td>
      </tr>
    <%- end %>
    </tbody>
  </table><br />
</div>

app/views/admin/users/edit.html.erb
<div class="page-header">
  <h1>Editing Member</h1>
</div>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<div class="page-header">
  <h1>Members</h1>
</div>
<%- sort_chapters_by_state(@chapters).each do |chapter| %>
  <%= render partial: "users_table", locals: { chapter: chapter, users: sort_users_by_role(chapter.users) } %>
<%- end %>

<%= render partial: "users_table", locals: { chapter: nil, users: User.orphaned } %>

app/views/admin/users/new.html.erb
<div class="page-header">
  <h1>New Member</h1>
</div>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dd><%= @user.role_list.map{|role_name| role_name.titleize}.join(', ') %></dd>
      <dt>Name</dt>
      <dd><%= @user.name %></dd>
      <dt>Email</dt>
      <dd><%= @user.email %></dd>
      <dt>Chapter</dt>
      <dd><% if @user.chapter %><%= @user.chapter.name %><% end %></dd>
    </dl>
    <%- if !@user.address.nil? %>
    <dl class="dl-horizontal">
      <dt>Address</dt>
      <dd><%= @user.address.line_1 %></dd>
      <dd><%= @user.address.line_2 %></dd>
      <dd><%= @user.address.city %>, <% if !@user.address.state.nil? %><%= @user.address.state.name.titleize %><% end %> <%= @user.address.postal_code %></dd>
    </dl>
    <%- end %>
    <%= link_to edit_admin_user_path(@user) do%>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    <%- end %>
  </div>
</div>