config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

    devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

	namespace :admin do
    root 'chapters#index'

		resources :pages, only: [:index, :new, :edit, :create, :update, :destroy]
		resources :users, only: [:index, :show, :new, :edit, :create, :update]

		resources :chapters do
			resources :pages
		end
	end

	get 'home/:title' => 'home#index'
	get 'states/:id', to: 'states#show', as: :state
	get 'chapters/:id', to: 'chapters#show', as: :chapter
	get 'pages/:id', to: 'pages#show', as: :page

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  include Navigable

  belongs_to :state

  has_one :page, :as => :pageable, dependent: :destroy
  has_many :users, dependent: :nullify

  validates :name, presence: true,
    uniqueness: true
  #validates :state_id, presence: true

  scope :adopted, -> { where.not(state_id: nil) }
  scope :orphaned, -> { where(state_id: nil) }
  #scope :sorted, -> { includes(:state).order("states.name or chapters.name ASC") }

  def titleize_name
    name.titleize
  end

  #def self.sorted
    #chapters = self.all.includes(:state)
    #chapters.sort{|x,y| (x.state_id? ? x.state.name : x.name) <=> (y.state_id? ? y.state.name : y.name)}
  #end
end

app/controllers/admin/chapters_controller.rb
class Admin::ChaptersController < Admin::BaseController
  def new
    @chapter = Chapter.new
    @chapter.build_public_navigation
  end

  def create
    @chapter = Chapter.new(chapter_params)

    if @chapter.save
      redirect_to [:admin, @chapter]
    else
      render 'new'
    end
  end

  def index
    @orphaned_chapters = Chapter.orphaned.includes(:public_navigation)
    @adopted_chapters = Chapter.adopted.includes(:public_navigation, :state)
  end

  def edit
    @chapter = Chapter.find(params[:id])
  end

  def show
    @chapter = Chapter.includes(:users).find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:id])

    if @chapter.update(chapter_params)
      redirect_to [:admin, @chapter]
    else
      render 'edit'
    end
  end

  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy

    redirect_to admin_chapters_path
  end

  private
    def chapter_params
      params.require(:chapter).permit(:name, :state_id, public_navigation_attributes:[:id, :active])
    end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def show
    @chapter = Chapter.find(params[:id])
  end
end

app/helpers/admin/chapters_helper.rb
module Admin::ChaptersHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
	def sort_chapters_by_state chapters
		chapter_sort_hash = {}

		chapters.each do |chapter|
			if chapter.state
				chapter_sort_hash[chapter.state.name] = chapter
			else
				chapter_sort_hash[chapter.name] = chapter
			end
		end

		sorted_chapters = []
		chapter_sort_hash.sort_by{|key, chapter| key.downcase}.each do |key, chapter|
			sorted_chapters.push(chapter)
		end

		return sorted_chapters
	end
end

app/views/admin/chapters/_chapter_table.html.erb
<%- if chapters.any? %>
<div class="panel panel-default">
  <table class="table">
    <caption><%= description %></caption>
    <thead>
      <tr>
        <th>Name</th>
        <th>State</th>
        <th>Show on website</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% sort_chapters_by_state(chapters).each do |chapter| %>
      <tr>
        <td><%= chapter.name %></td>
        <td>
        <%- if chapter.state %>
          <%= chapter.state.titleize_name %>
        <%- else %>
          N/A
        <%- end %>
        </td>
        <td>
          <%- if chapter.public_navigation.active %>
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <%- end %>
        </td>
        <td><%= link_to admin_chapter_path(chapter) do%>
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <%- end %>
        </td>
        <td><%= link_to edit_admin_chapter_path(chapter) do%>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        <%- end %>
        </td>
        <td><%= link_to admin_chapter_path(chapter), method: :delete, data: { confirm: 'Are you sure?' } do%>
          <span class="glyphicon glyphicon-remove" style="color:red" aria-hidden="true"></span>
        <%- end %>
        </td>
      </tr>
    <%- end %>
    </tbody>
  </table><br />
</div>
<%- end %>

app/views/admin/chapters/_form.html.erb
<%= form_for [:admin, @chapter] do |f| %>
  <%- if @chapter.errors.any? %>
    <div class="alert alert-warning" role="alert">
      <h2>
        <%= pluralize(@chapter.errors.count, "error") %> prohibited
        this chapter from being saved:
      </h2>
      <ul>
        <% @chapter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <%- end %>

  <div class="input-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Chapter Name", :'aria-describedby' => "Name of Chapter"%>
  </div>

  <p>
    <%= f.label :state %><br>
    <%= f.collection_select :state_id, State.order(:name), :id, :titleize_name, prompt: true %>
  </p>

  <%= f.fields_for :public_navigation do |public_navigation| %>
    <%= render :partial => 'public_navigation', :locals => {:f => public_navigation} %>
  <%- end %>

  <p>
  <div class="input-group">
    <%= f.submit "Save", class: "btn btn-primary btn-sm " %>
    <%= link_to 'Back', admin_chapters_path, class: 'btn btn-default btn-sm'%>
  </div>
<%- end %>

app/views/admin/chapters/_form_for_page.html.erb
<% if @chapter.page %>
<div class='bs-callout'>
  <h2>Page</h2>
  <p>
    <strong>Title:</strong>
    <%= @chapter.page.title %>
  </p>

  <p>
    <strong>Sub-Title:</strong>
    <%= @chapter.page.sub_title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @chapter.page.body %>
  </p>
</div>

  <%= link_to 'Edit', edit_admin_chapter_page_path(@chapter, @chapter.page), class: 'btn btn-primary btn-sm' %>
  <%= link_to 'Delete Page', [:admin, @chapter, @chapter.page],
    method: :delete,
    data: { confirm: 'Are you sure?' },
    class: 'btn btn-danger btn-sm'
  %>
<% else %>
  <h2>Add a Page:</h2>
  <%= render :partial => 'admin/pages/form_polymorphic', :locals => {:pageable => @chapter} %>
<% end %>

app/views/admin/chapters/_public_navigation.html.erb
<fieldset class="form-group">
  <%= f.label "Display on Homepage" %>
  <div class="input-group">
		<%= f.check_box :active, {}%>
  </div>
</fieldset>

app/views/admin/chapters/edit.html.erb
<div class="page-header">
  <h1>Editing Chapter</h1>
</div>
 
<%= render 'form' %>
<%= render 'form_for_page' %>

app/views/admin/chapters/index.html.erb
<div class="page-header">
  <h1>Chapters</h1>
</div>
<%= render partial: "chapter_table", locals: { chapters: @adopted_chapters, description: 'Chapters asociated with a State are grouped, on the home page, under their State.' } %>
<%= render partial: "chapter_table", locals: { chapters: @orphaned_chapters, description: 'Chapters not asociated with a State are displayed on the home page' } %>

app/views/admin/chapters/new.html.erb
<div class="page-header">
  <h1>New Chapter</h1>
</div>

<%= render 'form' %>

app/views/admin/chapters/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= @chapter.name %></div>
  <!-- Table -->
  <table class="table">
    <thead>
      <tr>
        <th>State</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
        <%- if @chapter.state %>
          <%= @chapter.state.titleize_name %>
        <%- else %>
          Chapter not associated with a State
        <%- end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'Edit', edit_admin_chapter_path(@chapter), class: 'btn btn-primary btn-sm' %>
<%= link_to 'Back', admin_chapters_path, class: 'btn btn-default btn-sm' %>

<%= render 'form_for_page' %>
<%= render partial: "admin/users/users_table", locals: { chapter: @chapter, users: sort_users_by_role(@chapter.users) } %>